---
# Deployment configuration
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app: test-service
  replicas: 1
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
      - name: test-service
        image: test-service:latest
        # NOTE: I had to set the policy to 'Never', or else the Kubernetes couldn't find the local image on my machine.
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
# Service configuration. This creates a `NodePort` service that exposes our deployment outside the cluster at
# the specified port.
kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-service
  ports:
    - port: 8080
      nodePort: 30080
      name: http
